name: Checks

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Build Docker images
      #   run: docker compose build

      - name: Run Tests
        run: |
          docker compose up -d
          docker compose exec -T app sh -c "python manage.py test"

      - name: Run Linting
        id: lint
        run: docker compose exec -T app sh -c "flake8"

      # - name: Shut down services
      #   run: docker compose down
